
on: [ push, pull_request ]

name: Automated release build

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and upload release assets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      # build the code before creating the release, GO and Solidity first for faster failures
      - name: Build GO
        run: |
          cd module
          make

      - name: Set ENV var for GOPATH
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV

      - name: Build Solidity artifacts
        run: cd solidity && npm ci && npm run typechain

      - name: Build contract deployment script into a static binary
        run: cd solidity && npm ci && npm run compile-deployer

      - name: Build Rust x86_64
        run: |
          cargo install cross
          cd orchestrator
          cross build --target x86_64-unknown-linux-musl --release --all
